### ISSUE TITLE
How does this work with iframes and xpath?

### ISSUE THREAD

**Issue by Aracknid416** [ranorex/selocity-extension#1]
Some feedback on my initial usage. Not sure if I'm using it correctly...

I have a lot of iframes in my client, and using this tool to spy on something in my client, the proposed xpath is valid but only if the iframe is the root, where as the rxpath is correct from the top of the DOM.

There is no obvious indication (to me) that the element spied on is within an iframe. In Selenium I'd have to know the frames in order to switch to them first. Maybe there could be some way to provide all the parent frames to switch to as part of the path (and the user would need to know to remove this from the xpath) or some extra info provided in the "List of selectors" area to indicate this, such as another icon that when clicked gave the parent frame(s) info?

For example, I have this structure for a tree view display in my client. The div[1] element is the first entry line of the tree and contains an image for expand/collapse, the icon for this entry, and the span of text for this entry. Below is the path to the span (text) of the first entry:

DOM/body/div[@id='treediv']/iframe[@id='tree']//body/table//iframe[@id='ifr1']//body//div[@id='TreeBorder']/div[@id='Tree']/div[1]/span

When I select the text, I get the provided xpath as "//div[@id='Tree']/div[1]/span[.='TheTextDisplayed']"

1) I'd like to know I need to switch to the frames:
        a) iframe[@id='tree']
        b) iframe[@id='ifr1']
2) I don't think the text for the span should be included, since this is dynamic in this case. Not to big a deal, I can manually remove it.
3) If I copy the xpath or the rxpath to the test selector area and hit enter, it doesn't find the element if I add extra iframe info to it at the front. For example if I say look for //iframe//iframe//div[@id='Tree']/div[1]/span it won't find the span.

I saw that there was a tool coming for Selenium to allow it to use RxPath... Is that coming from you? I'd be interested in using that. I'm trying to get my Ranorex scripts to run in Edge using Webdriver and since everything is my own custom framework in VisualStudio (not using Ranorex Studio), one of my challenges is converting my strings of desired RxPaths to elements I want to find into Xpath to use with the WebDriver.

Let me know if you need more info.

Thanks,

Aracknid

NOTE: I edited issue 3 above after submitting it.

**Comment by rxse** [comment]
Hi Aracknid

Thank you very much for your detailed and valuable feedback. 

From my point of view, you are using Selocity correctly. Currently Selocity does not provide an obvious indication that the element spied on is within an iframe or not.  However, there are good news: We spotted this issue already and have it on our list in one of the top spots :)

> There is no obvious indication (to me) that the element spied on is within an iframe. In Selenium I'd have to know the frames in order to switch to them first. Maybe there could be some way to provide all the parent frames to switch to as part of the path (and the user would need to know to remove this from the xpath) or some extra info provided in the "List of selectors" area to indicate this, such as another icon that when clicked gave the parent frame(s) info?

Good suggestion. We will definitely keep your proposal in mind when thinking about how we solve the indication feature. 

> If I copy the xpath or the rxpath to the test selector area and hit enter, it doesn't find the element if I add extra iframe info to it at the front. For example if I say look for //iframe//iframe//div[@id='Tree']/div[1]/span it won't find the span. 

We’ll fix this issue together with the indication.

> I saw that there was a tool coming for Selenium to allow it to use RxPath... Is that coming from you?

Yes, we will provide a tool for Selenium and other popular End2End-Testing frameworks early 2018 (such as webdriverIO). We would be happy if you can look on it by assigning to our [beta program](https://www.ranorex.com/selocity/browser-extension.html). Each feedback will help us solving the right problems.

**Comment by rxse** [comment]
Hi again @Aracknid416 !
We are pleased to inform you that, with the latest Ranorex Selocity release, we updated the iFrame support feature! More about that in the [changelog](https://github.com/ranorex/selocity-extension/blob/master/CHANGELOG.md#100).

Also, we are proud to present the official Ranorex Webtestit version 1.0.0! You can check it out and [download the free trial here ](https://www.ranorex.com/webtestit/)
