### ISSUE TITLE
Values shall be enclosed with single quotes

### ISSUE THREAD

**Issue by pragmatictesters** [ranorex/selocity-extension#3]
Reporting against 
Version: 0.6.0
Updated: June 21, 2018

Sample CSS generated 
[name="txtUsername"]

Sample XPath generated 
/html//input[@id='txtUsername']

It is better if attribute's values in CSS  are enclosed with single quotes as in XPaths.
Additional negation character is automatically added when the CSS is copied into IDE (IntelliJ IDEA). This should be handled manually if IDE does negate the double quotations.

Appreciate if CSS values are enclosed with single quotes.

**Comment by rxse** [comment]
Fixed with version 0.7.0. CSS selectors are enclosed with single quotes!
